apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploy.name }}-{{ .Values.deploy.branch }}-deployment
  namespace: {{ .Values.deploy.namespace }}
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.deploy.name }}-{{ .Values.deploy.branch }}-app
  replicas: {{ .Values.deploy.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploy.name }}-{{ .Values.deploy.branch }}-app
    spec:
      containers:
      - name: nodejs
        image: thebadalov/k8s-deployment:{{ .Values.deploy.tag }}
        imagePullPolicy: Always
      imagePullSecrets:
      - name: myregistrykey
      dnsPolicy: Default
