apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploy.name }}-{{ .Values.deploy.branch }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.deploy.name }}-{{ .Values.deploy.branch }}-app
  ports:
    - name: http
      port: 3000
      protocol: TCP
