name: Build and push Docker image

on:
  push:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
       
    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2
    
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Cat Helm Values File
      id: cat
      run: echo "::set-output name=result_tag::$(cat helm/main.yaml | grep -o 'github[^,]*')"
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_REGISTRY }}:github-V${{ github.run_id }}
