name: Build and push Docker image

on:
  push:
    branches:
      - main
      - test
    tags:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
       
    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2
    
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/thedatabaseme/hello-world
        flavor: latest=true
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: thebadalov/k8s-deployment:${{ steps.meta.outputs.tags }}
